# Generated by Django 3.0.8 on 2020-07-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healFlow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('weapon_damage', models.FloatField(null=0)),
                ('mind', models.FloatField(null=0)),
                ('determination', models.FloatField(null=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
