# Generated by Django 3.0.8 on 2020-07-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healFlow', '0002_auto_20200720_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamuhTimeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('damage', models.FloatField(null=0)),
                ('time', models.TimeField(null=0)),
            ],
        ),
    ]
