# Generated by Django 3.0.8 on 2020-07-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healFlow', '0003_ramuhtimeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramuhtimeline',
            name='time',
            field=models.DurationField(),
        ),
    ]
