# Generated by Django 3.0.8 on 2020-07-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healFlow', '0007_auto_20200721_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramuhtimeline',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
