# Generated by Django 3.0.8 on 2020-07-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healFlow', '0008_auto_20200721_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('potency', models.FloatField(null=0)),
                ('cooldown', models.FloatField(null=0)),
                ('gcd', models.FloatField(null=0)),
                ('weave', models.FloatField(null=0)),
                ('duration', models.FloatField(null=0)),
                ('optimalWeave', models.FloatField(null=0)),
            ],
        ),
    ]
