# Generated by Django 3.0.8 on 2020-07-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healFlow', '0009_abilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramuhtimeline',
            name='time_seconds',
            field=models.FloatField(default=0, null=0),
            preserve_default=False,
        ),
    ]
