# Generated by Django 3.0.8 on 2020-07-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healFlow', '0010_ramuhtimeline_time_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramuhtimeline',
            name='time_seconds_next_damage',
            field=models.FloatField(default=0, null=0),
        ),
    ]
