# Generated by Django 3.0.8 on 2020-07-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healFlow', '0012_abilitytimeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilitytimeline',
            name='init',
            field=models.BooleanField(default=False),
        ),
    ]
