# Generated by Django 3.0.8 on 2020-07-22 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healFlow', '0013_abilitytimeline_init'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abilitytimeline',
            old_name='init',
            new_name='made',
        ),
    ]
