# Generated by Django 3.0.3 on 2020-07-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healFlow', '0014_auto_20200722_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilitytimeline',
            name='ogcd',
            field=models.FloatField(default=0, null=0),
        ),
    ]
