# Generated by Django 3.0.3 on 2020-07-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healFlow', '0015_abilitytimeline_ogcd'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilitytimeline',
            name='ogcdPosition',
            field=models.FloatField(default=0, null=0),
        ),
    ]
